[ids]
*

[main]
leftalt = layer(alt)
leftmeta = layer(mac_cmd)
capslock = layer(caps)

[mac_cmd:C]
c = C-insert
x = S-delete
v = S-insert

[caps]
h = M-left
l = M-right
f = M-pageup
j = C-A-S-M-j
q = layer(caps_q)

[caps_q]
h = C-A-S-M-h
d = C-A-S-M-d
f = C-A-S-M-f
enter = C-A-S-M-enter
o = C-A-S-M-o
