# READ FIRST: PUT THIS INTO ~/config/alacritty/
[env]
TERM = "xterm-256color"

[window]
padding.x = 5
padding.y = 5

decorations = "Buttonless"

[font]
normal.family = "MesloLGS Nerd Font Mono"

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]
