#!/bin/sh
set -eu

if [ "$#" -lt 2 ]; then
    echo "usage: focus-or-spawn <app-id> <command> [args...]" >&2
    exit 2
fi

app_id="$1"
shift

id="$(niri msg -j windows | jq -r --arg app "$app_id" '
    map(select(.app_id == $app))
    | sort_by(.focus_timestamp.secs // 0, .focus_timestamp.nanos // 0)
    | last.id // empty
')"

if [ -n "$id" ]; then
    exec niri msg action focus-window --id "$id"
else
    exec "$@"
fi
